### ISSUE TITLE
Performance comparison with Muller's PPG

### ISSUE THREAD

**Issue by ShilinC** [iRath96/variance-aware-path-guiding#1]
Hi,

Thank you for sharing the good work. I compiled and tested the code on the pool scene but I got worse results than Muller's original PPG. I don't know why. Here is the setup I use:

"nee": "never"
"sampleCombination": "discard"
"spatialFilter": "nearest"
"directionalFilter": "nearest"
"distribution": "radiance"
"diStrategy": "no"
"bsdfSamplingFractionLoss": "none"
max depth: 10

For both this code and Muller's PPG code from his git repo, I use the same setting as above. Also, I start both with 4 spp and end up with 1024 spp. Muller's original PPG took 3.58 mins and this one took 3.87 mins.

Please see the attached images. I don't know why the rendering result using your code contains a lot of speckles. Is there anything that I missed? Thanks!

Muller's original PPG:
![muller_pool](https://user-images.githubusercontent.com/11979931/88351749-30306100-cd0c-11ea-8d95-fa1587bb9461.png)

this work:
![variance_pool](https://user-images.githubusercontent.com/11979931/88351770-40e0d700-cd0c-11ea-9ac0-9c7b2b6c96b3.png)

Best,
Shilin

**Comment by ShilinC** [comment]
I also tried running the kitchen scene, but the results are still noisy with lots of speckles:

Here I set "full" in "distribution":

![kitchen_myrun](https://user-images.githubusercontent.com/11979931/88361829-3be14f00-cd2f-11ea-91b8-6419f7a3ad13.png)

This is still worse than Muller's PPG. I'm totally confused now. Could you give me some hint?

**Comment by iRath96** [comment]
Hi,

just for clarification: this repository contains both Müller's guiding target function (`distribution = "radiance"`) and the one proposed in our paper (`distribution = "full"`).

Our evaluation uses the following parameters:
| parameter | value |
|-----------|-----|
| `nee` | `always` (note that when disabling NEE, our distribution takes longer to improve over radiance-based distributions, as we have discussed in our supplemental document) |
| `sampleCombination` | `discard` |
| `spatialFilter` | `box` (takes a bit longer to train, but creates less noise in the guiding caches) |
| `directionalFilter` | `box` (as recommended by Müller et al.) |
| `distribution` | `full` (when setting this to `radiance`, this implementation is equivalent to Müller's PPG) |
| `diStrategy` | `no` |
| `bsdfSamplingFractionLoss` | `none` (the Adam optimizer can produce artifacts in some scenes for both methods) |
| `sTreeThreshold` | `2000` (Müller recommends `4000`, but lower values accelerate learning both for PPG and our distribution) |
| `dTreeThreshold` | `0.005` (Müller recommends `0.01`, but this again improves results significantly for both methods) |
| `sppPerPass` | `1` |

Hope this helps. Let me know if you need additional information.

**Comment by ShilinC** [comment]
Ok after I change nearest to box, then the speckles are gone. Thanks!
